import { AIModel } from './types';

export const TOOLS: AIModel[] = [
  // 国内 (Domestic)
  {
    name: 'DeepSeek',
    org: '深度求索',
    descCn: '推理能力极其扎实的国产开源大模型。',
    descEn: 'A domestic open-source model with exceptionally solid reasoning ability.',
    url: 'https://chat.deepseek.com',
    mono: 'DS',
    color: '#4D6BFE',
    section: 'cn',
  },
  {
    name: 'Kimi',
    org: '月之暗面',
    descCn: '拥有超长上下文理解能力，擅长高效分析长文档。',
    descEn: 'Equipped with ultra-long context understanding, excelling at analyzing long documents.',
    url: 'https://kimi.com',
    mono: 'K',
    color: '#00C2A0',
    section: 'cn',
  },
  {
    name: 'Doubao',
    org: '字节跳动',
    descCn: '字节跳动出品，智能对话与语音交互非常流畅顺手。',
    descEn: 'Created by ByteDance, offering smooth conversational capabilities and vocal interactions.',
    url: 'https://www.doubao.com',
    mono: '豆',
    color: '#D98A3D',
    section: 'cn',
  },
  {
    name: 'Zhipu Qingyan',
    org: '智谱 AI',
    descCn: '清华系团队精心打造的全能型智能助手。',
    descEn: 'A versatile AI assistant crafted by a dedicated Tsinghua University spin-off team.',
    url: 'https://chatglm.cn',
    mono: '智',
    color: '#7C5CFC',
    section: 'cn',
  },
  {
    name: 'GLM Open Platform',
    org: '智谱 · BigModel',
    descCn: 'GLM 大模型系列 API 服务与开发者在线体验中心。',
    descEn: 'The API portal and online playground for GLM series large models.',
    url: 'https://open.bigmodel.cn',
    mono: 'GLM',
    color: '#3FA9A0',
    section: 'cn',
  },
  {
    name: 'MiniMax',
    org: '海螺 AI / MiniMax',
    descCn: '支持多模态创作，语音合成与拟真对话极为流畅。',
    descEn: 'Supports multimodal generation with incredibly natural voice synthesis and conversation.',
    url: 'https://www.minimaxi.com',
    mono: 'M',
    color: '#12B76A',
    section: 'cn',
  },
  {
    name: 'MiMo',
    org: '小米',
    descCn: '小米自研大模型，提供多场景体验与自适应交互。',
    descEn: 'Developed by Xiaomi, providing multi-scenario experiences and adaptive interaction.',
    url: 'https://mimo.mi.com',
    mono: '米',
    color: '#FF6900',
    section: 'cn',
  },
  {
    name: 'Qwen',
    org: '阿里巴巴',
    descCn: '阿里巴巴主导的开源大模型，拥有一流的中英双语能力。',
    descEn: 'An open-source flagship model by Alibaba with top-tier bilingual capabilities.',
    url: 'https://www.qianwen.com',
    mono: '千',
    color: '#FF5630',
    section: 'cn',
  },
  {
    name: 'Ernie Bot',
    org: '百度',
    descCn: '百度精心打造的知识增强型大语言模型服务入口。',
    descEn: 'An enhanced knowledge-driven large language model service by Baidu.',
    url: 'https://yiyan.baidu.com',
    mono: '文',
    color: '#2468F2',
    section: 'cn',
  },
  {
    name: 'Tencent Yuanbao',
    org: '腾讯',
    descCn: '腾讯出品的 AI 助手，内置混元与 DeepSeek 双重深度模型。',
    descEn: 'An AI assistant by Tencent with integrated Hunyuan and DeepSeek dual engines.',
    url: 'https://yuanbao.tencent.com',
    mono: '元',
    color: '#E3A008',
    section: 'cn',
  },
  {
    name: 'iFlytek Spark',
    org: '科大讯飞',
    descCn: '语音交互见长，拥有极强的方言识别与行业知识储备。',
    descEn: 'Excels in voice dialogue, offering strong dialect recognition and vertical knowledge.',
    url: 'https://xinghuo.xfyun.cn',
    mono: '星',
    color: '#F2542D',
    section: 'cn',
  },
  // 全球 (Global)
  {
    name: 'ChatGPT',
    org: 'OpenAI',
    descCn: '全球生态最成熟、功能全面的通用智能助手。',
    descEn: 'The world\'s most mature and fully-featured general-purpose AI assistant.',
    url: 'https://chatgpt.com',
    mono: 'GPT',
    color: '#10A37F',
    section: 'global',
  },
  {
    name: 'Claude',
    org: 'Anthropic',
    descCn: '注重逻辑推理、深度写作与高安全性的顶尖 AI 助手。',
    descEn: 'A premier AI assistant focusing on logical reasoning, writing, and security.',
    url: 'https://claude.ai',
    mono: 'C',
    color: '#D97757',
    section: 'global',
  },
  {
    name: 'Gemini',
    org: 'Google DeepMind',
    descCn: '谷歌原生多模态大模型，深度融入谷歌全套云生态。',
    descEn: 'Google\'s native multimodal model, deeply integrated with the Google ecosystem.',
    url: 'https://gemini.google.com',
    mono: 'Ge',
    color: '#4C8DF6',
    section: 'global',
  },
  {
    name: 'Grok',
    org: 'xAI',
    descCn: '实时检索社交网络，性格幽默直接、充满极客风格。',
    descEn: 'Retrieves social network feeds in real-time with a direct, witty geek personality.',
    url: 'https://grok.com',
    mono: 'X',
    color: '#E5E7EB',
    section: 'global',
  },
  {
    name: 'NVIDIA API Catalog',
    org: '英伟达',
    descCn: '基础模型体验中心，提供顶级的计算加速与云端接口。',
    descEn: 'Foundation model directory, offering high-performance acceleration and APIs.',
    url: 'https://build.nvidia.com',
    mono: 'NV',
    color: '#76B900',
    section: 'global',
  },
  {
    name: 'Perplexity',
    org: 'Perplexity AI',
    descCn: '答案自带精准引用来源，最受科研与调研青睐的检索引擎。',
    descEn: 'Delivers answers with precise source citations, favored for research and surveys.',
    url: 'https://www.perplexity.ai',
    mono: 'P',
    color: '#1FB8CD',
    section: 'global',
  },
  {
    name: 'Microsoft Copilot',
    org: '微软',
    descCn: '深度嵌入微软办公全家桶的生产力效率智能助手。',
    descEn: 'An efficiency-focused productivity assistant deeply integrated with Microsoft 365.',
    url: 'https://copilot.microsoft.com',
    mono: 'Co',
    color: '#0078D4',
    section: 'global',
  },
  {
    name: 'Meta AI',
    org: 'Meta',
    descCn: '基于 LLaMA 开源生态的多平台、大覆盖范围的智能助手。',
    descEn: 'A multi-platform assistant with extensive coverage, powered by LLaMA.',
    url: 'https://www.meta.ai',
    mono: 'Me',
    color: '#7C7EFF',
    section: 'global',
  },
  {
    name: 'Mistral Vibe',
    org: 'Mistral AI',
    descCn: '欧洲最受瞩目的开源力量，严格遵循高规格数据安全合规。',
    descEn: 'Europe\'s leading open-source force, adhering to strict data security compliance.',
    url: 'https://chat.mistral.ai',
    mono: 'Vi',
    color: '#FA520F',
    section: 'global',
  },
];
